# We alias the child chart names to avoid having to deal with hyphenated 
# YAML keys.

dependencies:
- name: weave-scope-agent
  alias: agent
  condition: agent.enabled, global.agentEnabled
- name: weave-scope-frontend
  alias: frontend
  condition: frontend.enabled, global.frontendEnabled
