# Where defaults exist, the values are set to them here.
# Values with no preferred or common defaults are set to empty strings.

global:

#  global.image: the image that will be used for this release
#  image: "weaveworks/scope"

#  global.imageTag: the version of Weave Scope desired for this release
#  imageTag: "1.6.2"

#  global.service.* sets the values for the service that provides access to the Weave Scope frontend
    service:

#  global.service.name: the short name desired for the frontend service
#  global.service.name is a global so we can access its value easily from the agent subchart
#      name: "weave-scope-app"

#  global.service.port: the port exposed by the Scope frontend service
#  global.service.port is a global so we can access its value easily from the agent subchart
#      port: 80

#  global.service.type: the frontend service type must be ClusterIP, NodePort or LoadBalancer
#  global.service.type is a global to keep it with the other values for configuring the frontend service
      type: "NodePort"

#frontend.* controls how the Scope frontend is installed
#frontend:

#  enabled: true

#  frontend.imagePullPolicy: controls when the image is pulled
#  imagePullPolicy: ""

#  frontend.containerPort: the port opened to the Scope frontend
#  containerPort: 4040

#  frontend.resources.*: controls requests/limits for the frontend
#  frontend.resources.* values are all optional
#  resources: 

#    requests:

#      frontend.resources.requests.cpu: CPU req. in MHz (m)
#      cpu: ""

#      frontend.resources.requests.memory: memory req. in MiB (Mi)
#      memory: ""

#    limits:

#      frontend.resources.limits.cpu: CPU limit in MHz (m)
#      cpu: ""

#      frontend.resources.limits.memory: memory limit in MiB (Mi)
#      memory: ""

#agent.* controls how the Weave Scope node agent pods are installed
#agent:

#  enabled: true

#  agent.imagePullPolicy: controls when the image is pulled
#  imagePullPolicy: ""

#  agent.probeToken is the token used to connect to Weave Cloud
#  agent.probeToken is not needed for connecting to non-cloud Scope frontends
#  probeToken: ""

#  agent.serviceAccount: the service account to be created for the agent
#  serviceAccount: "weave-scope"

#  agent.scopeFrontendAddr: the host:port of a Scope frontend to send data to
#  agent.scopeFrontendAddr is only needed for some cases where the frontend is deployed separately from the agent
#  scopeFrontendAddr: ""

#  agent.dockerBridge is the name of the Docker bridge interface
#  dockerBridge: "docker0"

#  agent.resources.*: controls requests/limits for the agent
#  agent.resources.* values are all optional
#  resources:

#    requests:

#      agent.resources.requests.cpu: CPU req. in MHz (m)
#      cpu: ""

#      agent.resources.requests.memory: memory req. in MiB (Mi)
#      memory: ""

#    limits:

#      agent.resources.limits.cpu: CPU limit in MHz (m)
#      cpu: ""

#      agent.resources.limits.memory: memory limit in MiB (Mi)
#      memory: ""
