image:
  repository: unguiculus/spilo
  tag: latest
  pullPolicy: Always

# How many postgres containers to spawn
replicas: 3

podAntiAffinity: soft

nodeSelector: {}

tolerations: []

# Resource requests and limits per pod
resources: {}
  # requests:
  #   cpu: 100m
  #   memory: 256Mi
  # limits:
  #   cpu: 500m
  #   memory: 512Mi

credentials:
  superuser: tea
  standby: pinacolada

useConfigMaps: false

walE:
  enable: false
  scheduleCronJob: 00 01 * * *
  retainBackups: 2
  s3Bucket:
  gcsBucket:
  kubernetesSecret:
  backupThresholdMegabytes: 1024
  backupThresholdPercentage: 30

persistentVolume:
  enabled: true
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  annotations: {}

cleanup:
  image:
    repository: quay.io/coreos/hyperkube
    tag: v1.8.4_coreos.0
    pullPolicy: IfNotPresent
