imagePullPolicy: IfNotPresent

# The image to use. Spilo is the dockerized Patroni
spilo:
  # this image was built from https://github.com/zalando/spilo/tree/master/postgres-appliance
  image: registry.opensource.zalan.do/acid/spilo-9.6
  version: 1.2-p17

# How many postgres containers to spawn
replicas: 5

podAntiAffinity: soft

nodeSelector: {}

tolerations: []

# Resource limits per replica
resources: {}
  # cpu: 100m
  # memory: 512Mi

# Node selector for Patroni pods
# nodeSelector:
#  cloud.google.com/gke-nodepool: highmem-pool

# Credentials used by Patroni
# * more information: https://github.com/zalando/patroni/blob/master/docs/SETTINGS.rst#postgresql
credentials:
  superuser: tea
  admin: cola
  standby: pinacolada

## Distribution Configuration stores. Please note that only one of the following stores should be selected.
etcd:
  enable: true
  deployChart: true
  # if not deploying etcd chart, fill-in value for etcd host (etcd.default.svc.cluster.local)
  host:
  # leave blank to use vendored etcd chart
  discovery:

zookeeper:
  enable: false
  deployChart: false
  # if not deploying etcd chart, fill-in list of ZooKeeper cluster members in format: 'host1:port1','host2:port2','etc...'
  hosts:

walE:
  enable: false
  scheduleCronJob: 00 01 * * *
  retainBackups: 2
  s3Bucket:
  gcsBucket:
  kubernetesSecret:
  backupThresholdMegabytes: 1024
  backupThresholdPercentage: 30

persistentVolume:
  enabled: true
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  annotations: {}
  subPath: ""
  mountPath: "/home/postgres/pgdata"
