apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "helm_std_labels" . | indent 4 }}
    component: agent
  name: weave-scope
  annotations:
    {{- include "scope_annotations" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: weave-scope
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount | default "weave-scope" }}
    namespace: {{ .Release.Namespace }}
