apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    {{- include "weave-scope.helm_std_labels" . | indent 4 }}
  name: {{ template "weave-scope.fullname" . }}
  annotations:
    {{- include "weave-scope.annotations" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ template "weave-scope.name" . }}
      release: {{ .Release.Name }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "weave-scope.helm_std_labels" . | indent 8 }}
    spec:
      tolerations:
        - effect: NoSchedule
          operator: Exists
      containers:
        - name: {{ template "weave-scope.name" . }}
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: "{{ .Values.global.image.pullPolicy }}"
          args:
            - '--no-app'
            - '--probe.docker.bridge={{ .Values.dockerBridge }}'
            - '--probe.docker=true'
            - '--probe.kubernetes=true'
            {{- if .Values.global.probeToken }}
            - '--probe-token={{ .Values.global.probeToken }}'
            {{- else if .Values.global.scopeFrontendAddr }}
            - {{ .Values.global.scopeFrontendAddr }}
            {{- else }}
            - {{ template "weave-scope.frontend.fullname" . }}.{{ .Release.Namespace }}.svc:{{ .Values.global.service.port }}
            {{- end }}
          securityContext:
            privileged: true
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
            - name: scope-plugins
              mountPath: /var/run/scope/plugins
            - name: sys-kernel-debug
              mountPath: /sys/kernel/debug
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: scope-plugins
          hostPath:
            path: /var/run/scope/plugins
        - name: sys-kernel-debug
          hostPath:
            path: /sys/kernel/debug
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "weave-scope.fullname" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
