{{- $svcname := "weave-scope" -}}
{{- $svcport := 80 -}}

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    {{- include "weave-scope.helm_std_labels" . | indent 4 }}
    component: agent
  name: {{ template "weave-scope.fullname" . }}-agent
  annotations:
    {{- include "weave-scope.annotations" . | indent 4 }}
spec:
  selector: 
    matchLabels:
      app: {{ template "weave-scope.name" . }}
      release: {{ .Release.Name }}
      component: agent
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "weave-scope.helm_std_labels" . | indent 8 }}
        component: agent
    spec:
      tolerations:
        - effect: NoSchedule
          operator: Exists
      containers:
        - name: agent
          image: {{ .Values.global.image }}:{{ .Values.global.imageTag }}
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          args:
            - '--no-app'
            - '--probe.docker.bridge={{ .Values.dockerBridge }}'
            - '--probe.docker=true'
            - '--probe.kubernetes=true'
            {{- if .Values.global.probeToken }}
            - '--probe-token={{ .Values.global.probeToken }}'
            {{- else if .Values.global.scopeFrontendAddr }}
            - >-  {{ .Values.global.scopeFrontendAddr }}
            {{- else }}
            - >-
              {{- if .Values.global.service }}
              {{ .Values.global.service.name }}.{{ .Release.Namespace }}.svc:{{ .Values.global.service.port }}
              {{- else }}
              {{ $svcname }}.{{ .Release.Namespace }}.svc:{{ $svcport }}
              {{- end }}
            {{- end }}
          securityContext:
            privileged: true
          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          {{- end }}
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
            - name: scope-plugins
              mountPath: /var/run/scope/plugins
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: scope-plugins
          hostPath:
            path: /var/run/scope/plugins
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: {{ .Values.serviceAccountName }}
