{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "weave-scope.helm_std_labels" . | indent 4 }}
  name: {{ template "weave-scope.fullname" . }}
  annotations:
    {{- include "weave-scope.annotations" . | indent 4 }}
{{- end }}
