apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "weave-scope.helm_std_labels" . | indent 4 }}
    component: agent
  name: {{ .Values.serviceAccountName }}
  annotations:
    {{- include "weave-scope.annotations" . | indent 4 }}
