apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    {{- include "weave-scope.helm_std_labels" . | indent 4 }}
    component: frontend
  name: {{ template "weave-scope.fullname" . }}-app
  annotations:
    {{- include "weave-scope.annotations" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ template "weave-scope.name" . }}
      release: {{ .Release.Name }}
      component: frontend
  template:
    metadata:
      labels:
        {{- include "weave-scope.helm_std_labels" . | indent 8 }}
        component: frontend
    spec:
      containers:
        - name: app
          image: {{ .Values.global.image }}:{{ .Values.global.imageTag }}
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          args:
            - '--no-probe'
          ports:
            - containerPort: {{ required "You must supply a container port to open" .Values.containerPort }}
              protocol: TCP
          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          {{- end }}
  replicas: 1
