apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    {{- include "weave-scope.helm_std_labels" . | indent 4 }}
  name: {{ template "weave-scope.fullname" . }}
  annotations:
    {{- include "weave-scope.annotations" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "weave-scope.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "weave-scope.helm_std_labels" . | indent 8 }}
    spec:
      containers:
        - name: {{ template "weave-scope.name" . }}
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: "{{ .Values.global.image.pullPolicy }}"
          args:
            - "--no-probe"
          ports:
            - name: http
              containerPort: 4040
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
