apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "weave-scope.helm_std_labels" . | indent 4 }}
    component: frontend
  name: {{ .Values.global.service.name }}
  annotations:
    {{- include "weave-scope.annotations" . | indent 4 }}
spec:
  ports:
    - name: {{ required "You must specify a service name" .Values.global.service.name }}
      port: {{ required "You must specify a port the frontend service should listen on" .Values.global.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
  selector:
    app: {{ template "weave-scope.name" . }}
    release: {{ .Release.Name }}
    component: frontend
  type: {{ required "You must specify a supported service type (ClusterIP, NodePort or LoadBalancer)" .Values.global.service.type }}
