{{- $svcname := "weave-scope" -}}
{{- $svcport := 80 -}}
{{- $svctype := "ClusterIP" -}}

apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "helm_std_labels" . | indent 4 }}
    component: frontend
  {{- if .Values.global.service }}
  name: {{ .Values.global.service.name | default $svcname }}
  {{- else }}
  name: {{ $svcname }}
  {{- end }}
  annotations:
    {{- include "scope_annotations" . | indent 4 }}
spec:
  ports:
    {{- if .Values.global.service }}
    - name: {{ .Values.global.service.name | default $svcname }}
      port: {{ .Values.global.service.port | default $svcport }}
    {{- else }}
    - name: {{ $svcname }}
      port: {{ $svcport }}
    {{- end }}
      targetPort: {{ .Values.containerPort | default 4040 }}
      protocol: TCP
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    component: frontend
  {{- if .Values.global.service }}
  type: {{ .Values.global.service.type | default $svctype }}
  {{- else }}
  type: {{ $svctype }}
  {{- end }}
