apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "weave-scope.helm_std_labels" . | indent 4 }}
  name: {{ template "weave-scope.fullname" . }}
  annotations:
    {{- include "weave-scope.annotations" . | indent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.global.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app: {{ template "weave-scope.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.global.service.type }}
